apiVersion: v1
kind: Pod
metadata:
  name: server-pod2
  annotations:
    k8s.v1.cni.cncf.io/networks: macvlan-conf
  labels:
    component: web1
spec:
  containers:
    - name: server
      image: xuxant/tomcat
      ports:
        - containerPort: 8081